apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6143452974367986087
  namespace: default
spec:
  interval: 5m0s
  path: clusters/flux+cluster2/context/6143452974367986087
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6143452974367986087"
  targetNamespace: default
status: {}
